### ISSUE TITLE
Enhancement: add support different ddos attack type

### ISSUE THREAD

**Issue by kastakhov** [sflow-rt/ddos-blackhole#2]
Hi,
Can you add support for different ddos ​​atack mitigation? Such as udp amp (use ntp, dns and another) - possible allocate with source port in packets, tcp syn | ack flood, packet fragmentation (udp 0). 
It will add more flexibilyti in ddos mitigation.

**Comment by sflow-rt** [comment]
The current scheme of looking at total packets per second targeting an address will catch any UDP reflection attack (NTP, DNS, Memcache, etc) as well as ICMP, UDP and TCP flood attacks. Using more specific flow signatures adds complexity and risks missing novel attack vectors covered by the existing method, and since null routing drops all traffic to the target, there isn't much benefit in additional attack signature information.

BGP FlowSpec offers a more targeted method of blocking specific attacks - [Real-time DDoS mitigation using sFlow and BGP FlowSpec](https://blog.sflow.com/2017/07/real-time-ddos-mitigation-using-sflow.html). I am currently working on a new sFlow-RT application focused on FlowSpec mitigation.

**Comment by sflow-rt** [comment]
[DDoS Protect](https://github.com/sflow-rt/ddos-protect) includes support for different DDoS attack types and adds BGP Flowspec support for mitigation.
